### ISSUE TITLE
Connection refused on proxy and admin services

### ISSUE THREAD

**Issue by shalabhaggarwal** [Mashape/kong-dist-google-cloud#1]
Hi,

I followed the same steps as outlined in the README.
When I curl the admin and proxy services I get the connection refused error.

`curl: (7) Failed to connect to <IP Address> port 8001: Connection refused`

Is this repo usable yet or there is more to come before I can use it?
Let me know if you need any more info from my end on this.
Happy to help. :)

**Comment by shashiranjan84** [comment]
@shalabhaggarwal  Well this repo is still in test mode, I was trying something new yesterday to separate out proxy and admin services so that admin service can have protected access. Test was failing because GKE not allowing more than one external ip (some limit for free account). I ll try to dig further. Meanwhile you can try one commit back.

**Comment by shashiranjan84** [comment]
@shalabhaggarwal try now, make sure you have at least two `STATIC_ADDRESSES` available for the Zone in which you creating the cluster. I am closing the ticket for now, feel free to reopen if you run into any issue.
